[aeons]
projectName = "bitmap-font"

parameters = ["-dce full"]

defines = ["kha_html5_disable_automatic_size_adjust"]

[aeons.html5]
disableContextMenu = true
canvasId = "aeonsGame"
scriptName = "aeons"

# To enable lDtk support add "ldtk-haxe-api" and "deepnightLibs". Install them using haxelib.
# To enable nape physics add "nape-haxe4". Install this using haxelib.
libraries = []

# To enable lDtk add "use_ldtk".
# To enable nape add "use_nape"
defines = []
