[aeons]
projectName = "ldtk-platformer"

libraries = [
  "ldtk-haxe-api",
  "deepnightLibs"
]

defines = [
  "use_ldtk",
  "kha_html5_disable_automatic_size_adjust"
]

parameters = ["-dce full"]

[aeons.html5]
disableContextMenu = true
canvasId = "aeonsGame"
scriptName = "aeons"


[[atlas]]
name = "backgrounds"
saveFolder = "assets"
folders = ["atlasImages/backgrounds"]
trimmed = false
extrude = 1
packMethod = "basic"
noData = true
maxWidth = 156

[[atlas]]
name = "tiles"
saveFolder = "assets"
folders = ["atlasImages/tiles"]
trimmed = false
extrude = 1
packMethod = "basic"
noData = true
maxWidth = 400

[[atlas]]
name = "sprites"
saveFolder = "assets"
folders = ["atlasImages/sprites"]
