[aeons]
projectName = "ldtk-platformer"

libraries = [
  "ldtk-haxe-api",
  "deepnightLibs"
]

defines = [
  "use_ldtk"
]

parameters = ["-dce full"]

[aeons.html5]
disableContextMenu = true
canvasId = "aeonsGame"
scriptName = "aeons"


[[atlas]]
name = "atlas"
saveFolder = "assets"
folders = ["atlasImages"]
trimmed = true
extrude = 1
packMethod = "optimal"